remove hardcoded package name from shell

diff --git a/manager/src/main/assets/rish b/manager/src/main/assets/rish
--- a/manager/src/main/assets/rish
+++ b/manager/src/main/assets/rish
@@ -12,14 +12,16 @@ if [ $(getprop ro.build.version.sdk) -ge 34 ]; then
     echo "On Android 14+, app_process cannot load writable dex."
     echo "Attempting to remove the write permission..."
     chmod 400 $DEX
-  fi
-  if [ -w $DEX ]; then
-    echo "Cannot remove the write permission of $DEX."
-    echo "You can copy to file to terminal app's private directory (/data/data/<package>, so that remove write permission is possible"
-    exit 1
+    if [ -w $DEX ]; then
+      echo "Cannot remove the write permission of $DEX."
+      echo "You can copy to file to terminal app's private directory (/data/data/<package>, so that remove write permission is possible"
+      exit 1
+    else
+      echo "Write permission was removed successfully."
+    fi
   fi
 fi
 
-# Replace "PKG" with the application id of your terminal app
-[ -z "$RISH_APPLICATION_ID" ] && export RISH_APPLICATION_ID="PKG"
+# Replace "PKG" with the application id of your terminal app and "MANAGER_PKG" with the application id of Shizuku
+[ -z "$RISH_APPLICATION_ID" ] && export RISH_APPLICATION_ID="PKG" && export MANAGER_APPLICATION_ID="MANAGER_PKG"
 /system/bin/app_process -Djava.class.path="$DEX" /system/bin --nice-name=rish rikka.shizuku.shell.ShizukuShellLoader "$@"
